apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: {{ .Values.namespace }}
data:
  DATABASE_VENDOR: {{ .Values.keycloak_opt.keycloak_database_vendor }}
  DATABASE_HOST: {{ .Values.keycloak_opt.keycloak_database_host }}
  DATABASE_NAME: {{ .Values.keycloak_opt.keycloak_database_name }}