apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DATABASE_USER: {{ .Values.keycloak_opt.keycloak_database_user }}
  DATABASE_PASSWORD: {{ .Values.keycloak_opt.keycloak_database_password }}
  ADMIN_USER: {{ .Values.keycloak_opt.keycloak_admin_user }}
  ADMIN_PASSWORD: {{ .Values.keycloak_opt.keycloak_admin_password }}
