replicaCount: 1

image:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: "15.2"

namespace: "home-rp"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "org-db"

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 5432

ingress:
  enabled: false

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

postgres_opt:
  postgresqlUsername: "b3JnX3Rlc3RfdXNlcg=="
  postgresqlPassword: "b3JnX3Rlc3RfdXNlcg=="
  postgresqlDatabase: "org"
  postgresqlHost: "org-db"
