apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret_name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DB_USER: {{ .Values.options.DB_USER }}
  DB_PWD: {{ .Values.options.DB_PWD }}
  DB_DSN: {{ .Values.options.DB_DSN }}
